application: proppy-dpxdt
module: worker
version: 1
runtime: custom
api_version: 1
threadsafe: yes

vm: true
manual_scaling:
  instances: 5
vm_health_check:
  enable_health_check: False

handlers:
- url: /.*
  script: run_worker.sh # ignored
